// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xQags9bPWItWGOiwwir5TFpsADDtYag',
    appId: '1:614967291168:web:b5264e1512da9d258ffb45',
    messagingSenderId: '614967291168',
    projectId: 'kamaldodeen-3764d',
    authDomain: 'kamaldodeen-3764d.firebaseapp.com',
    storageBucket: 'kamaldodeen-3764d.appspot.com',
    measurementId: 'G-QW888N1SC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlAFvUeo-Ad7HMsyc9gusbpO1NU8ziVkI',
    appId: '1:614967291168:android:fc4e6a11a8da39928ffb45',
    messagingSenderId: '614967291168',
    projectId: 'kamaldodeen-3764d',
    storageBucket: 'kamaldodeen-3764d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQDTbNzzzFP76_Tei8zKlBz1eMci62XY',
    appId: '1:614967291168:ios:c82c8850daa876918ffb45',
    messagingSenderId: '614967291168',
    projectId: 'kamaldodeen-3764d',
    storageBucket: 'kamaldodeen-3764d.appspot.com',
    iosBundleId: 'com.usul.usul',
  );
}
